### PR TITLE
remove useless packages

### PR DESCRIPTION
**Pull request by Marie59**

### CODE REVIEW

**Comment by bgruening** [comment]
It builds at least :)

**Review by bgruening — APPROVED** [review]

**Comment by Marie59** [comment]
And locally it works fine !

**Comment by bgruening** [comment]
This merge has NOT created a new container. Whenever you think its ready to get a new container you need to create a new version.

**Comment by Marie59** [comment]
Do you see any thing else that should be changed ? I think it's quite ready now

**Comment by bgruening** [comment]
Ship it!

**Pull request merged**
